name: redstone_app
description: RedStone Crypto Investment Platform - A MLM-based crypto investment app with daily returns and referral system

publish_to: 'none'

version: 2.0.6+8

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State Management
  provider: ^6.1.1
  riverpod: ^2.6.1
  flutter_riverpod: ^2.6.1
  
  # Networking
  http: ^1.2.0
  dio: ^5.3.3
  
  # Local Storage
  shared_preferences: ^2.2.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  
  # UI Components
  flutter_svg: ^2.0.9
  cached_network_image: ^3.4.0
  shimmer: ^3.0.0
  flutter_spinkit: ^5.2.0
  
  # Navigation
  go_router: ^12.1.3
  
  # Authentication
  crypto: ^3.0.3
  jwt_decoder: ^2.0.1
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^3.5.7
  
  # Utilities
  intl: ^0.19.0
  url_launcher: ^6.2.1
  share_plus: ^7.2.2
  package_info_plus: ^5.0.1
  device_info_plus: ^9.1.2
  
  # Firebase
  # Firebase packages removed (not used)
  
  # Charts
  fl_chart: ^0.65.0
  
  # Security
  local_auth: ^2.1.7
  biometric_storage: ^5.0.1
  
  # Icons
  cupertino_icons: ^1.0.2
  feather_icons: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/logo/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icon.png"
  min_sdk_android: 21